#!/usr/bin/env zsh
sudo apt-get install -y \
    build-essential \
    curl \
    fluid-soundfont-gm \
    fontconfig \
    fonts-freefont-ttf \
    git \
    git-core \
    git-lfs \
    gstreamer1.0-plugins-{bad,base,good,ugly} \
    gstreamer1.0-{omx,alsa} \
    libavcodec-dev \
    libavformat-dev \
    libbz2-dev \
    libffi-dev \
    libfreetype6-dev \
    libgl1-mesa-dev \
    libgles2-mesa-dev \
    libgstreamer1.0-dev \
    libjpeg-dev \
    liblzma-dev \
    libmtdev-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libportmidi-dev \
    libreadline-dev \
    libsdl-image1.2-dev \
    libsdl-mixer1.2-dev \
    libsdl-ttf2.0-dev \
    libsdl1.2-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libsmpeg-dev \
    libsqlite3-dev \
    libssl-dev \
    libswscale-dev \
    libtiff5-dev \
    libx11-6 \
    libx11-dev \
    llvm \
    make \
    pkg-config \
    python-dev \
    python-openssl \
    python-setuptools \
    python3-dev \
    python3-numpy \
    python3-opengl \
    python3-setuptools \
    timgm6mb-soundfont \
    tk-dev \
    wget \
    xclip \
    xfonts-100dpi \
    xfonts-75dpi \
    xfonts-base \
    xfonts-cyrillic \
    xsel \
    xz-utils \
    zlib1g-dev
